### Requer a extensão REST Client
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@URL = http://localhost:3003/api/billing-cycles

@OPEN_URL = http://localhost:3003/open-api

###
POST {{OPEN_URL}}/signup HTTP/1.1
content-type: application/json

{
    "name": "Cricano de Tal",
    "email": "cricano@teste.com.br",
    "password": "P@ss1234",
    "confirm_password": "P@ss1234"
}

###
# @name signIn
POST {{OPEN_URL}}/login HTTP/1.1
content-type: application/json

{
    "email": "cricano@teste.com.br",
    "password": "P@ss1234"
}

###

@token = {{signIn.response.body.token}}

###
POST {{OPEN_URL}}/validate-token HTTP/1.1
content-type: application/json

{
    "token": "{{token}}"
}

###
GET {{URL}} HTTP/1.1
Authorization: {{token}}

###
GET {{URL}}?skip=0&limit=2 HTTP/1.1
Authorization: {{token}}

###
GET {{URL}}/61ada44169a86f2bb4461315 HTTP/1.1
Authorization: {{token}}

###
POST {{URL}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

name=Agosto/2017
&month=8
&year=2017
&credits[0][name]=Salário Empresa
&credits[0][value]=7500
&credits[1][name]=Salário Professor
&credits[1][value]=1700
&debts[0][name]=Telefone
&debts[0][value]=22.9
&debts[0][status]=PAGO
&debts[1][name]=Condomínio
&debts[1][value]=420
&debts[1][status]=AGENDADO

###
PUT {{URL}}/61ada44169a86f2bb4461315 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

name=Fevereiro/2017
&month=2
&year=2017
&credits[0][name]=Salário Empresa
&credits[0][value]=6500
&credits[1][name]=Salário Professor
&credits[1][value]=2700
&debts[0][name]=Telefone
&debts[0][value]=86.9
&debts[0][status]=PAGO
&debts[1][name]=Condomínio
&debts[1][value]=430
&debts[1][status]=AGENDADO

###
DELETE  {{URL}}/61aed61d1156fc592ab408fb HTTP/1.1
Authorization: {{token}}

###
GET {{URL}}/count HTTP/1.1
Authorization: {{token}}

###
GET {{URL}}/summary HTTP/1.1
Authorization: {{token}}
